[package]
name = "macros"
version = "0.1.0"
authors = ["Elliot Bobrow <elliotgreybobrow@gmail.com>"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = "1.0"
quote = "1.0"
web = { version = "0.1.0", path = "../web" }
